# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-21 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='最后更新时间'),
        ),
    ]
